services:

    nginx-dev:
        build:
            context: ../
            dockerfile: docker/debian-nginx-ssl-ja3/Dockerfile
        hostname: nginx-dev
        container_name: nginx-ssl-ja3
        volumes:
            - ../:/build/nginx-ssl-ja3
        ports:
          - "443:443"
        expose:
          - 443
        network_mode: bridge
        tty: true
        privileged: true
        cap_add:
          - ALL

